baseURL = 'https://sonsdesbambous.com'
languageCode = 'fr'
title = 'Sons des Bambous'
theme = 'sonsdesbambous'
removePathAccents = true
[pagination]
  pagerSize = 20
[params]
  description = "Poésie vietnamienne en résonance française"
  author = "Sons des Bambous"

[taxonomies]
  tag = "tags"
[permalinks]
  poems = "/poemes/:slug/"
[slugify]
  [slugify.replacements]
    "œ" = "oe"
    "Œ" = "oe"
