baseURL = 'https://sonsdesbambous.com'
languageCode = 'fr'
title = 'Sons des Bambous'
theme = 'sonsdesbambous'
[pagination]
  pagerSize = 20
[params]
  description = "Poésie vietnamienne traduite en français"
  author = "Sons des Bambous"

[taxonomies]
  tag = "tags"
[permalinks]
  poems = "/poemes/:slug/"
